### ISSUE TITLE
Add tlroadmap

### ISSUE THREAD

**Issue by sobolevn** [igoradamenko/awesome-made-by-russians#28]
https://github.com/tlbootcamp/tlroadmap

**Comment by igoradamenko** [comment]
Do you know, who is the author of the repo?

There're three people in the org: https://github.com/orgs/tlbootcamp/people. Are all of them authors, or there is one “core maintainer”?

**Comment by sobolevn** [comment]
Egor Tolstoy and Stas Tsyganov are two original authors.

**Comment by igoradamenko** [comment]
Thanks! 🚀
