### ISSUE TITLE
Add ponyorm

### ISSUE THREAD

**Issue by sobolevn** [igoradamenko/awesome-made-by-russians#30]
https://github.com/ponyorm/pony

**Comment by igoradamenko** [comment]
Hm.

Are Alexander Kozlovsky and Alexey Malashkevich Russian?

**Comment by igoradamenko** [comment]
@kozlovsky, @amalashkevich, hey guys!

Would you mind if we add your project into the list?

**Comment by tigertv** [comment]
> Are Alexander Kozlovsky and Alexey Malashkevich Russian?

[Yes.](https://www.youtube.com/watch?v=NFpJxMrG_Lw)

**Comment by igoradamenko** [comment]
Thanks! 👍
