### ISSUE TITLE
Add dephell

### ISSUE THREAD

**Issue by sobolevn** [igoradamenko/awesome-made-by-russians#32]
https://github.com/dephell/dephell

**Comment by sobolevn** [comment]
CC @orsinium

**Comment by igoradamenko** [comment]
Hm. Do you know the name and surname of the author?

We have a kind of “code style” here, and trying to use real names instead of nicknames.

**Comment by igoradamenko** [comment]
Oh, there's one more cool project from the same author: https://github.com/life4/textdistance.

**Comment by tigertv** [comment]
Maybe, he is ['Никита Воронов'.](https://www.youtube.com/watch?v=JtdZyLfSNS8)

**Comment by igoradamenko** [comment]
@tigertv, definitely, thanks!

I've added both projects: https://github.com/igoradamenko/awesome-made-by-russians/commit/736471a46bcf078fe14305bc3daaf8dd39a0397b
