### ISSUE TITLE
Add yoksel/common-words

### ISSUE THREAD

**Issue by tensegrity666** [igoradamenko/awesome-made-by-russians#34]
https://github.com/yoksel/common-words

**Comment by igoradamenko** [comment]
Yeah, it would be great to add it, but I'm not sure how to transliterate author's name & surname correctly.

@yoksel, would you mind to help?

**Comment by yoksel** [comment]
Yulia Bukhvalova

I'm not sure this project will be useful for non-russian users — it's just english words & russian comments to them

**Comment by igoradamenko** [comment]
Well, I'm not sure either, but at the same time, I believe that this repo is mostly useful for Russian speaking users.

**Comment by igoradamenko** [comment]
Thanks!
