### ISSUE TITLE
Add Mediawiki API?

### ISSUE THREAD

**Issue by VorontsovIE** [igoradamenko/awesome-made-by-russians#35]
Not sure about number of stargazers as [mediawiki API](https://gerrit.wikimedia.org/g/mediawiki/core/) is not hosted on github. But it is indeed very popular project developed by [Yury Astrakhan](https://github.com/nyurik).

**Comment by igoradamenko** [comment]
Not sure what to do with it.

I've added the project into the list in #39. Let's say this issue is absorbed by #39.

Thank you anyway!
