### ISSUE TITLE
Vlang

### ISSUE THREAD

**Issue by slowernews** [igoradamenko/awesome-made-by-russians#63]
I believe [V lang](https://github.com/vlang/v) (18K stars) is also made by a russian.

**Comment by igoradamenko** [comment]
I think so, but I couldn't find any proof that @medvednikov is Russian.

**Comment by medvednikov** [comment]
I am :)

**Comment by igoradamenko** [comment]
Cool! I've added V in df16bca64d3d2a79b1e535be2091720df3bb8ab6.

Thanks!
