### ISSUE TITLE
Is Yegor Bugayenko a Russian?

### ISSUE THREAD

**Issue by egorsmkv** [igoradamenko/awesome-made-by-russians#64]
@yegor256 are you?

**Comment by igoradamenko** [comment]
Oops, you're right. 

https://www.linkedin.com/in/yegor256/

> Dnipropetrovs'kij Nacional'nij Universitet

I've removed link to Tacit in e13c3fe2387c3cced4d2a8989b511c46e71369c4.

But just to be sure, let's wait for Yegor's confirmation :-)

**Comment by yegor256** [comment]
@igoradamenko I'm russian, коллеги, все в порядке)
