### ISSUE TITLE
Add Ataraxia Linux

### ISSUE THREAD

**Issue by protonesso** [igoradamenko/awesome-made-by-russians#67]
Hey, there's a project made by Russian guy (me). Here's the link: https://github.com/ataraxialinux/ataraxia

**Comment by igoradamenko** [comment]
Hey!

Sorry, but we're accepting only the projects that have 1000+ stars:

https://github.com/igoradamenko/awesome-made-by-russians#contributing

But I saved your project in my private “waiting list”, and when it reaches 1000, I will add it 🐨

**Comment by protonesso** [comment]
gotcha thanks!
