### ISSUE TITLE
CSS Box-shadow Lib

### ISSUE THREAD

**Issue by andrejsharapov** [igoradamenko/awesome-made-by-russians#69]
Возможно, стоит рассмотреть и этот проект. Небольшой, но будет интересный для начинающих кодеров. https://github.com/madeas/box-shadows.css

**Comment by igoradamenko** [comment]
Увы, нет.

Всё же у этого списка есть формальные требования, под которые box-shadow.css пока не подходит:

https://github.com/igoradamenko/awesome-made-by-russians#contributing

> The project has more that 1000 stars on Github.

----

Тем не менее, я записал эту репу в свой список «ожидания», и как только она перешагнёт порог в 1k, я её сразу добавлю. Спасибо!
