### ISSUE TITLE
Trim trailing whitespace

### ISSUE THREAD

**Issue by AlekSi** [igoradamenko/awesome-made-by-russians#79]
README is full of trailing whitespaces. Trimming them will make sending PRs easier for people who have a "trim trailing whitespace on save" setting enabled in their editors.

**Comment by igoradamenko** [comment]
Usually I fix README using web editor, and those trailing whitespaces will be back anyway ¯\\\_(ツ)_/¯

I don't mind if someone trims all the trailing spaces in their PR. So I guess it's fine.

**Comment by AlekSi** [comment]
https://github.com/igoradamenko/awesome-made-by-russians/pull/82
